# Nginx Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx-web-label

  template:
    metadata:
      labels:
        app: nginx-web-label

    spec:
      containers:
        - name: nginx
          image: minmin88/std01-nginx:latest

          ports:
            - containerPort: 80

---
# Nginx Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer

  selector:
    app: nginx-web-label

  ports:
    - port: 80
      targetPort: 80